### ISSUE TITLE
main.cpp:45: undefined reference to `bgslibrary::algorithms::FrameDifference::FrameDifference()'

### ISSUE THREAD

**Issue by jdzon23** [andrewssobral/bgslibrary#107]
The error when i compile is "undefined reference" .I  clone the library and copy the package package_analysis && package_bgs into my project and make a config folder under my project folder im working with Netbeans IDE .

**Comment by andrewssobral** [comment]
Hi @jdzon23 , this error says that the FrameDifference.cpp file (and probably others *.c or *.cpp files) is not included in your compilation

**Comment by jesuinovieira** [comment]
If you are compiling in Linux OS, then (after install the library):

Assuming that the _libbgslibrary_core.so_ file is located in /usr/local/lib

======================================================

To solve this **temporarily** (only in this bash session):
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
$ export LD_LIBRARY_PATH

======================================================

To solve this **permanent**:
$ sudo echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> ~/.bashrc

======================================================

And to compile your program include this flag: $LD_LIBRARY_PATH/libbgslibrary_core.so

Should be like: $ g++ -std=c++14 Demo.cpp $LD_LIBRARY_PATH/libbgslibrary_core.so `pkg-config --cflags --libs opencv`
