### ISSUE TITLE
Is there an easier way to set parameters?

### ISSUE THREAD

**Issue by headdab** [andrewssobral/bgslibrary#110]
I realize that I  can change the corresponding xml file in the config directory to change parameters for each algorithm, but is this the easiest way?  

Its awkward to script things with this strategy.  I have to edit the file between runs.

Are there other options and/or ways to pass in parameters?

Thanks!

**Comment by andrewssobral** [comment]
Hello @headdab ,
Unfortunately not, but you can change manually the parameters of some algorithms before compilation, or bypassing the `loadConfig()` and `saveConfig()` functions.
