### ISSUE TITLE
 libopencv_video.so.3.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zuenko** [andrewssobral/bgslibrary#125]
>>> import libbgs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libopencv_video.so.3.3: cannot open shared object file: No such file or directory

**Comment by andrewssobral** [comment]
it seems you need to put the compiled OpenCV libs (libopencv_***.so) in your python/system path.
