### ISSUE TITLE
compilation errors when compiling against opencv 4

### ISSUE THREAD

**Issue by headdab** [andrewssobral/bgslibrary#128]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

**Describe the bug**
On ubunut17.10, using  apt installed boost 1.62 libraries, bgs library fails to compile.

I made several changes to get it to compile, but don't know if they are correct.
Please review and comment and, hopefully, check them or another fix in.
There are a total of 5 1-line changes described in detail below:

python3 to python in CMakeLists.txt
added #include <opencv2/core/types_c.h> to conversions.h
changed == 3 to >= 3 at 3 places in conversion.cpp

**To Reproduce**
> git clone https://github.com/andrewssobral/bgslibrary.git
> sudo apt-get install libboost-all-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-all-dev is already the newest version (1.62.0.1).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.

> cd bgslibrary/build
> cmake -DBGS_PYTHON_SUPPORT=ON -DBGS_PYTHON_VERSION=3 ..
-- BGSLIBRARY WITH PYTHON SUPPORT: ON
-- PYTHON VERSION: 3
-- OpenCV library status:
--     version: 4.0.0
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn_objdetect;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_hdf;opencv_hfs;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
--     include path: /usr/include;/usr/include/opencv
-- SEARCHING FOR BOOST COMPONENT FOR PYTHON 3
CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:1582 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:96 (find_package)

CMake Error at /usr/share/cmake-3.9/Modules/FindBoost.cmake:1898 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_python3

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:96 (find_package)

-- Boost library status:
--     version: 106200
--     libraries: 
--     include path: /usr/include
-- Python library status:
--     executable: /home/estes/git/cv/CV/bin/python3
--     version: 3.6.3
--     library: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
--     include path: /usr/include/python3.6m
-- NUMPY_INCLUDE_DIR: /home/estes/git/cv/CV/lib/python3.6/site-packages/numpy/core/include
-- Configuring incomplete, errors occurred!
See also "/home/estes/git/bgslibrary/build/CMakeFiles/CMakeOutput.log".

** Note that it can't find boost_python3

# edit CMakeLists.txt
  if(BGS_PYTHON_VERSION EQUAL 2)
    find_package(Boost REQUIRED COMPONENTS python)
  else()
    find_package(Boost REQUIRED COMPONENTS python) # was python3
  endif()

> cd build && rm -rf * && cmake -DBGS_PYTHON_SUPPORT=ON -DBGS_PYTHON_VERSION=3 ..
-- The C compiler identification is GNU 7.2.0                          
-- The CXX compiler identification is GNU 7.2.0                        
-- Check for working C compiler: /usr/bin/cc                           
-- Check for working C compiler: /usr/bin/cc -- works                  
-- Detecting C compiler ABI info   
-- Detecting C compiler ABI info - done                                
-- Detecting C compile features    
-- Detecting C compile features - done                                 
-- Check for working CXX compiler: /usr/bin/c++                        
-- Check for working CXX compiler: /usr/bin/c++ -- works               
-- Detecting CXX compiler ABI info 
-- Detecting CXX compiler ABI info - done                              
-- Detecting CXX compile features  
-- Detecting CXX compile features - done                               
-- BGSLIBRARY WITH PYTHON SUPPORT: ON                                  
-- PYTHON VERSION: 3               
-- Found OpenCV: /usr (found version "4.0.0")                          
-- OpenCV library status:          
--     version: 4.0.0              
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn_objdetect;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_hdf;opencv_hfs;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto                        
--     include path: /usr/include;/usr/include/opencv                  
-- SEARCHING FOR BOOST COMPONENT FOR PYTHON 3                          
-- Boost version: 1.62.0           
-- Found the following Boost libraries:                                
--   python                        
-- Found PythonInterp: /home/estes/git/cv/CV/bin/python3 (found suitable version "3.6.3", minimum required is "3")                            -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.3", minimum required is "3")                     -- Boost library status:           
--     version: 106200             
--     libraries: /usr/lib/x86_64-linux-gnu/libboost_python.so         
--     include path: /usr/include  
-- Python library status:          
--     executable: /home/estes/git/cv/CV/bin/python3                   
--     version: 3.6.3              
--     library: /usr/lib/x86_64-linux-gnu/libpython3.6m.so             
--     include path: /usr/include/python3.6m                           
-- NUMPY_INCLUDE_DIR: /home/estes/git/cv/CV/lib/python3.6/site-packages/numpy/core/include                                                    -- Configuring done                
-- Generating done                 
-- Build files have been written to: /home/estes/git/bgslibrary/build  

** Looks like it found everything

> make

** compile almost finishes, but we get errors about CV_MAX_DIM not being defined (first one is shown below)

/home/estes/git/bgslibrary/wrapper_python/utils/conversion.cpp:257:17: error: ‘CV_MAX_DIM’ was not declared in this scope                     
     if(ndims >= CV_MAX_DIM)                                                                                                                  

After adding:

#include <opencv2/core/types_c.h>

to conversion.h, I get:

/home/estes/git/bgslibrary/wrapper_python/utils/conversion.cpp: In member function ‘cv::Mat NDArrayConverter::toMat(const PyObject*)’:
/home/estes/git/bgslibrary/wrapper_python/utils/conversion.cpp:319:11: error: ‘class cv::Mat’ has no member named ‘refcount’
         m.refcount = refcountFromPyObject(o);

which I fixed by changing all

#if CV_MAJOR_VERSION == 3

to

#if CV_MAJOR_VERSION >= 3

in conversion.cpp

**Expected behavior**

**Screenshots**

Included in explanation above.

### System information
**Desktop (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

> lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

- **Python version (for issues related to the python wrapper)**: 

Its in the output above.

- **Java version (for issues related to the java wrapper)**: 
- **MATLAB version (for issues related to the matlab wrapper)**: 

**Additional context**

**Comment by headdab** [comment]
My fix to find boost_python doesn't wok.  It found the python 2.7 version.
I'm not sure ho to fix this.  To make things work locally, I changed the link in 

  /usr/lib/x86_64-linux-gnu

to point to the python 3.6 version.

I haven't worked with cmake enough to easily figure out how to fix this.

On a related note, without changing all the CV_MAJOR_VERSION == 3 to >= 3, knn and mog2 are going to have problems.

**Comment by andrewssobral** [comment]
Hi @headdab could you test with my last commit please? PR https://github.com/andrewssobral/bgslibrary/pull/137

I replaced Boost.Python with pybind11, so no more need Boost.

**Comment by headdab** [comment]
Did you see my comments?
Not sure if you would, since the patch has already been merged.
Thanks.

**Comment by andrewssobral** [comment]
Hi @headdab can I close this issue? Thanks
