### ISSUE TITLE
Need an example to integrate into android NDK library (via JNI)

### ISSUE THREAD

**Issue by kafan1986** [andrewssobral/bgslibrary#130]
Can you show me, how can I integrate the project in one of my android ndk library? I am confused about creating a folder where you store the xml files. Do these config files keep on changing? If not, I can place a default config file and pass the location to the library through an API (method), if any exists.

**Comment by andrewssobral** [comment]
Hi @kafan1986 , sorry for my very long feedback. Yes, the bgslibrary uses the config file every time when you run an algorithm. You can change the path of the config files, but it is a manual step, by changing the setup() function in the constructor of each algorithm.
