### ISSUE TITLE
Cannot find `libbgs.dylib` on Mac OS X.

### ISSUE THREAD

**Issue by w4-jonghoon** [andrewssobral/bgslibrary#138]
If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

**Describe the bug**
After following the instruction in the [Wrapper-Python page](https://github.com/andrewssobral/bgslibrary/wiki/Wrapper:-Python) on Mac OS X.
I cannot find `libbgs.dylib` file.
Instead, I got `libbgslibrary_core.dylib` file, and so I changed its name to `libbgs.so`, but I couldn't import `bgs` library.
```
$ cp build/libbgslibrary_core.dylib ./libbgs.so

$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bgs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bgs'
```

**To Reproduce**
1. go inside the build directory
```$ cd build```
2. configure build environment using cmake
```$ cmake -D BGS_PYTHON_SUPPORT=ON  ..```
3. build
```$ make ```
4. go up to the root of bgs library
```$ cd ..```
5. copy dylib file to 
```$ cp build/libbgslibrary_core.dylib ./libbgs.so```
6. try to import 
```
$ python
>>> import bgs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bgs'
```

**Expected behavior**
1. existing `libbgs.dylib` file in the `build` directory
2. importing is succeed

**Screenshots**

### System information
**Desktop (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.6
- **Python version (for issues related to the python wrapper)**: Python 3.6.5 :: Anaconda, Inc.
- **Java version (for issues related to the java wrapper)**:  N/A
- **MATLAB version (for issues related to the matlab wrapper)**: N/A

**Additional context**

**Comment by w4-jonghoon** [comment]
In MacOS, `bgs.cpython-36m-darwin.so` file is created, and it is enough to import.
So, I recommend you to fix the wiki-page: [Wrapper: Python](https://github.com/andrewssobral/bgslibrary/wiki/Wrapper:-Python)

**Comment by andrewssobral** [comment]
Thank you @w4-jonghoon for reporting this issue. I am fixing it.
Best,
Andrews
