### ISSUE TITLE
Question on ViBe

### ISSUE THREAD

**Issue by rbennum** [andrewssobral/bgslibrary#147]
Hello. I want to ask a question. I've read "bgslibrary/vibe-background-sequential.cpp" source file, and in lines 759-761, these are the codes:

    historyImage[index_neighbor + position[shift] * (3 * width) * height] = r;
    historyImage[index_neighbor + position[shift] * (3 * width) * height + 1] = g;
    historyImage[index_neighbor + position[shift] * (3 * width) * height + 2] = r;

So, is there any reason to put another `r` value into `historyImage` instead of `b` value?

Thank you.

**Comment by andrewssobral** [comment]
Thank you @rbennum for reporting this issue, I think this was a typo in the code, I am fixing it. 
*Sorry for my long delayed feedback to you*

**Comment by andrewssobral** [comment]
Fixed https://github.com/andrewssobral/bgslibrary/commit/7fb89288689bb83cd96350672bbf894d0ef5459d
