### ISSUE TITLE
Unresolved External: LNK2019

### ISSUE THREAD

**Issue by acrarshin** [andrewssobral/bgslibrary#150]
Here is the error: LNK2019	unresolved external symbol "public: __cdecl BackgroundSubtractorSuBSENSE::BackgroundSubtractorSuBSENSE(float,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64)" (??0BackgroundSubtractorSuBSENSE@@QEAA@M_K0000@Z) referenced in function "public: virtual void __cdecl bgslibrary::algorithms::SuBSENSE::process(class cv::Mat const &,class cv::Mat &,class cv::Mat &)" (?process@SuBSENSE@algorithms@bgslibrary@@UEAAXAEBVMat@cv@@AEAV45@1@Z)	BGS_pro	C:\Users\bgslibrary\BGS_pro\BGS_pro\SuBSENSE.obj	

It cannot find SubSENSE but I have included SuBSENSE.cpp as a Source file. Also have declared the associated header file. Is there something I am missing?
![screenshot 4](https://user-images.githubusercontent.com/39985470/51028504-f4f89200-15ac-11e9-9699-db0df1a6ffda.png)

My system details are:-
- Windows 10
- Running it on Visual 2015

Please note that,I have run the Frame Difference Algorithm and it worked seamlessly. I tried figuring this out but am unable to.

**Comment by andrewssobral** [comment]
It seems the problem is because SuBSENSE is in the wrong place (in your visual studio solution)...and the SuBSENSE also have other dependences like `package_bgs/LBSP` folder.
I think the best is to use CMake to construct your Visual Studio solution/project.

**Comment by acrarshin** [comment]
I have added all the dependencies but the problem still persists.
Will try building it through CMake
Thanks
