### ISSUE TITLE
Is it possible to build python package without using third_party/pybind11 ?

### ISSUE THREAD

**Issue by jiapei100** [andrewssobral/bgslibrary#167]
Hi, Andrew:

How is everything? Glad to see you upgrade **bgslibrary** to version 3... ^_^

My issue:
Is it possible to build python package without using **third_party/pybind11** ?

I just successfully built the C/C++ version.
Trying

```console
python setup.py build
```

with the following **ERROR** message:

```python
CMake Error at CMakeLists.txt:161 (add_subdirectory):
  The source directory

    ....../bgslibrary/modules/pybind11

  does not contain a CMakeLists.txt file.
```

However, I've **ALREADY**manually installed **pybind11**:

```console
longervision-GT72-6QE% pip show pybind11
Name: pybind11
Version: 2.3.0
Summary: Seamless operability between C++11 and Python
Home-page: https://github.com/pybind/pybind11
Author: Wenzel Jakob
Author-email: wenzel.jakob@epfl.ch
License: BSD
Location: ~/.local/lib/python3.7/site-packages
Requires: 
Required-by:
```

Is there a way for users to build **bgslibrary** based on customized **pybind11**?

Thank you

Pei

**Comment by andrewssobral** [comment]
Hi @jiapei100 , thanks a lot! ;)
I think this error is related because you may forgot to clone the repository with the `--recursive` parameter, like this:
`git clone --recursive https://github.com/andrewssobral/bgslibrary.git`
this will clone also the submodules required by bgslibrary like pybind11.
Please let me know if this solve your issue

**Comment by jiapei100** [comment]
@andrewssobral 

hmmm.. There might have 2 solutions:
1) The FIRST one is your solution, which is NOT my preference.
2) I think there is a SECOND solution? Because I've ALREADY manually installed **pybind11** under _.local/lib/python3.7/site-packages_, we may be able to ignore the recursive **third_party**, but based on the existing **pybind11**????

**Comment by andrewssobral** [comment]
@jiapei100 
You may need to modify the [CMakeLists.txt](https://github.com/andrewssobral/bgslibrary/blob/master/CMakeLists.txt) file by:
```
#find_package(pybind11 REQUIRED)    #uncomment this line
add_subdirectory(modules/pybind11) #comment this one
```
you may also need to comment this line https://github.com/andrewssobral/bgslibrary/blob/master/CMakeLists.txt#L209
However, if it still not working, you may need to look at this issue https://github.com/pybind/pybind11/issues/1379
Not sure if PIP install the cmake file from pybind, but it seems that conda yes.
Hope this helps you.

**Comment by jiapei100** [comment]
@andrewssobral 

My bad... It looks it's NOT just 
```console
pip install pybind11 --user
```

but I need to build and install the [C++ version of pybind11](https://github.com/pybind/pybind11), which is OK...

Thank you Andrew... Close the issue now...
