### ISSUE TITLE
/usr/bin/ld: cannot find -lopencv_dep_cudart

### ISSUE THREAD

**Issue by yao177** [andrewssobral/bgslibrary#169]
I met a problem when I tried to build the program.

`$ make`

> Linking CXX shared library libbgslibrary_core.so
> /usr/bin/ld: cannot find -lopencv_dep_cudart
> collect2: error: ld returned 1 exit status
> CMakeFiles/bgslibrary_core.dir/build.make:2639: recipe for target 'libbgslibrary_core.so' failed
> make[2]: *** [libbgslibrary_core.so] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bgslibrary_core.dir/all' failed
> make[1]: *** [CMakeFiles/bgslibrary_core.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2

I think it doesn't need CUDA, but how to fix it.

**Comment by andrewssobral** [comment]
Hi @yao177 , thanks for reporting this issue. Yes, it's strange, because bgslib do not use CUDA.

**Comment by yao177** [comment]
Oh, I found a solution. To add `-DCUDA_USE_STATIC_CUDA_RUNTIME=OFF` can fix it.

**Comment by andrewssobral** [comment]
Great, thank you @yao177 for this info.
