### ISSUE TITLE
Unable to install pybgs with opencv-python pip

### ISSUE THREAD

**Issue by shubham162019** [andrewssobral/bgslibrary#172]
I have installed opencv-python using pip command, but while trying to install pybgs using pip, I get the following error which says :

By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "OpenCV", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "OpenCV" with any
      of the following names:
    
        OpenCVConfig.cmake
        opencv-config.cmake
    
      Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
      "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-8eq0c4r_/pybgs/build/temp.linux-x86_64-3.5/CMakeFiles/CMakeOutput.log".
    error: command 'cmake' failed with exit status 1
Does the above essentially mean that, opencv has to be build for using bgslibrary and a pip install of the same will not work?

**Comment by andrewssobral** [comment]
Hi @shubham162019 , 
Yes, unfortunately you need to install opencv lib.
The opencv-python package is limited to python scripts only,
As the core of bgslibrary is on C++, and the pybgs is just a wrapper around it, so when you do `pip install pybgs` it will download the C++ source code and compile the python wrapper locally.

**Comment by shubham162019** [comment]
Thanks.
