### ISSUE TITLE
error compiling on OSX with Opencv 4.2.0

### ISSUE THREAD

**Issue by phenix-chen** [andrewssobral/bgslibrary#175]
**Describe the bug**
error compiling on OSX with Opencv 4.2.0

**To Reproduce**
```
cd bgslibrary/build
cmake ..
make
```

**Expected behavior**
``` shell
[  1%] Building CXX object CMakeFiles/bgslibrary_core.dir/src/algorithms/LBP_MRF/MEImage.cpp.o
In file included from /home/opencv/4.2.0_1/include/opencv4/opencv2/opencv.hpp:74,
                 from /home/bgslibrary/src/algorithms/LBP_MRF/MEImage.cpp:1:
/home/bgslibrary/src/algorithms/LBP_MRF/MEImage.cpp: In member function 'void bgslibrary::algorithms::lbp_mrf::MEImage::GradientVisualize(int, int)':
/home/bgslibrary/src/algorithms/LBP_MRF/MEImage.cpp:1287:64: error: could not convert 'cv::Scalar_<double>((double)255, (double)255, (double)255, (double)0)' from 'cv::Scalar' {aka 'cv::Scalar_<double>'} to 'CvScalar'
 1287 |             cvLine(ME_CAST_TO_IPLIMAGE(cvImg), Point1, Point2, CV_RGB(255, 255, 255), 1, 8);
      |                                                                ^~~~~~
      |                                                                |
      |                                                                cv::Scalar {aka cv::Scalar_<double>}
make[2]: *** [CMakeFiles/bgslibrary_core.dir/src/algorithms/LBP_MRF/MEImage.cpp.o] Error 1
make[1]: *** [CMakeFiles/bgslibrary_core.dir/all] Error 2
make: *** [all] Error 2
```

### System information
macOS Catalina 10.15.3
Opencv 4.2.0
gcc 9.2 or clang 11(Both were tested)

**Additional context**

**Comment by andrewssobral** [comment]
Hi @phenix-chen , thanks for opening this issue, I confirm the bug.
I am working on it.

**Comment by andrewssobral** [comment]
Hi @phenix-chen I did a fix for this issue as you can see here https://github.com/andrewssobral/bgslibrary/pull/176
Please, let me know if it's working well for you.

**Comment by phenix-chen** [comment]
> Hi @phenix-chen I did a fix for this issue as you can see here #176
> Please, let me know if it's working well for you.

I've compiled successfully now. Thanks.

**Comment by andrewssobral** [comment]
Thank you @phenix-chen !

**Comment by frnhfr** [comment]
I have the same problem on Ubuntu now with the Opencv 4.4.0 when i run

`pip install pybgs`

# System information
Ubuntu 18.04
Opencv 4.4.0
gcc 8.4.0

**Comment by CenekAlbl** [comment]
Hi, I am facing the same issue on Ubuntu 20.04 with OpenCV 4.2.0 when running  
```
pip install pybgs
```

gcc version 9.3.0
