### ISSUE TITLE
run multilayer in qt gui with detect mode

### ISSUE THREAD

**Issue by SabraHashemi** [andrewssobral/bgslibrary#186]
Hi
in your qt gui we don't have any option to active detect mode
it is only on learn mode
and in learn mode it dont produce ,yml file.
can you explain how should i use it?
 if it needed to write our main, how it should be? (in c++)

**Comment by andrewssobral** [comment]
Hi @sabrabano0 , I'm sorry for my delayed feedback to you.
Yes, you're right. In fact, when you run the algorithm it produces a configuration file in the `config` folder. You can open it, and change the from `learn` to `detect` mode. Hope this helps you.

**Comment by sabrabano0** [comment]
thank you that solved my  problem.
