### ISSUE TITLE
Why does the following three foreground people exist all the time?

### ISSUE THREAD

**Issue by JiananYuan** [andrewssobral/bgslibrary#202]
Hi~ BGS is an excellent and nice work for CV research. I'm excited to run the example demo. However, when I select the AdaptiveSelectiveBackgroundLearning algorithm, the initial 3 people exist in all the video time. I mean, when the initial 3 people start moving to another place, the white foreground should move accordingly rather than keep in the same place. The 3 people region can be seen in the picture I marked below. 

![image](https://user-images.githubusercontent.com/53621620/109593347-b981fe80-7b4b-11eb-87a8-cbf9615677e9.png)

The project I currently do need to remove the initial white region. How can I fix this problem? Thx~

**Comment by JiananYuan** [comment]
Ah, I know that if the init frames don't contain moving people, then the effect is correct! But are there any solutions to solve the sutiation I mention above? Thank you!

**Comment by andrewssobral** [comment]
Hi @JiananYuan 
Sorry for my delayed feedback to you,

In fact, the AdaptiveSelectiveBackgroundLearning algorithm isn't the good choice if you have initial objects moving in the initial frames. It works like the StaticFrameDifference algorithm.

For your case, the best is to select another algorithm that updates the background model constantly like GMM, KNN, PBAS and others.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/483114/180655113-6ad8302e-1ff6-482c-a254-3ec01ce1a559.png">
