### ISSUE TITLE
What's the default algorithm used in bgs?

### ISSUE THREAD

**Issue by 1187697147** [andrewssobral/bgslibrary#204]
Hi, 
I have built this repo, when I use run_video.sh, I felt condused about which algorithm did you used.
Since there are many algorithms in demo2.py, so I wonder the default one.

**Comment by andrewssobral** [comment]
Hello @1187697147 , 
The default algorithm is the `Frame Difference`, defined in the `config/FrameProcessor.xml` file.

**Comment by 1187697147** [comment]
Okay, thanks for your reply!



---Original---
From: "Andrews Cordolino ***@***.***&gt;
Date: Sun, Apr 4, 2021 17:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [andrewssobral/bgslibrary] What's the default algorithm used in bgs? (#204)




 
Hello @1187697147 ,
 The default algorithm is the Frame Difference, defined in the config/FrameProcessor.xml file.

**Comment by andrewssobral** [comment]
You're welcome!
