### ISSUE TITLE
why using abs(dist*dist) for the one channel image in PBAS.cpp

### ISSUE THREAD

**Issue by batman47steam** [andrewssobral/bgslibrary#218]
https://github.com/andrewssobral/bgslibrary/blob/1d9d7ca15c934ceb366cd1b19ed7f223974ba6e5/package_bgs/PBAS/PBAS.cpp#L213

In PBAS.cpp for the three channel image, we compute dist like sqrt(a^2+b^2+c^2)，but for the one channel image shouldn't we just compute distance like **abs(a)**  `dist = abs(((double)B_Col_Pts.at(0).at(index)[i] - ((double)*currentFeaturesC_Pt.at(0))) ` not `dist = abs((((double)B_Col_Pts.at(0).at(index)[i] -
            ((double)*currentFeaturesC_Pt.at(0)))*((double)B_Col_Pts.at(0).at(index)[i] - ((double)*currentFeaturesC_Pt.at(0))))` which means **abs(a*a)**, a is short for the `((double)B_Col_Pts.at(0).at(index)[i] - ((double)*currentFeaturesC_Pt.at(0))` distance

**Comment by andrewssobral** [comment]
Hi @batman47steam,
Thank you for bringing this issue to our attention.

**Comment by andrewssobral** [comment]
Issue fixed https://github.com/andrewssobral/bgslibrary/commit/0b2462bf7cb99740e256137cb900ef753f23ea52
