### ISSUE TITLE
Unable to Install pybgs from PyPI(via pip install) on Google Colab Ubuntu 20.04 LTS  Instance

### ISSUE THREAD

**Issue by avadhut-00** [andrewssobral/bgslibrary#220]
**Describe the bug**
I am trying to install pybgs on Google Colab Instance and I was getting an error when executing a : pip3 install pybgs

**The error that I am getting is pasted below:**
````
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pybgs
  Using cached pybgs-3.3.0.post0.tar.gz (622 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pybgs
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pybgs (setup.py) ... error
  ERROR: Failed building wheel for pybgs
  Running setup.py clean for pybgs
Failed to build pybgs
Installing collected packages: pybgs
  error: subprocess-exited-with-error
  
  × Running setup.py install for pybgs did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for pybgs ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pybgs

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
````

**To Reproduce**
I have attached the Google Colab Notebook that has public access ----> [pybgs google colab notebook](https://colab.research.google.com/drive/1AZias6wLFaRWxMKaQFvQ64XxYl1nFy9W?usp=sharing)

**Expected behavior**
Installation should be successful as I am installing on a Ubuntu OS which is supported by the library

**Screenshots**
![pybgs_error](https://user-images.githubusercontent.com/112175709/226362444-e6f30988-4c3e-4caf-8ebe-2662517772dd.PNG)

### System information
**Desktop (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):---->Ubuntu 20.04.5 LTS**:
- **Python version (for issues related to the python wrapper):---->3.9.16**: 
- **Java version (for issues related to the java wrapper):----> NA**: 
- **MATLAB version (for issues related to the matlab wrapper):----> NA**: 

**Additional context**

**Comment by nebilibrahim22** [comment]
@avadhut-00 
I had the same issue just now but on Ubuntu 18.

I believe it's a CMake issue not on your side.

For now, I would just do this pip or pip3 install instead: pip install pybgs==3.2.0.post1

**Comment by avadhut-00** [comment]
@nebilibrahim22 
yes I was able to install pybgs using : **pip3 install pybgs==3.2.0.post1** but many of the algorithms raised an exception when invoked.The public Google Colab Notebook that contains the demo script that calls various algorithms present in the library: [notebook](https://colab.research.google.com/drive/1AZias6wLFaRWxMKaQFvQ64XxYl1nFy9W?usp=sharing)
