### ISSUE TITLE
Bgslibrary库是针对视频的  如何针对图片，我想只提供一两张图片  然后获取到背景  这样可以么

### ISSUE THREAD

**Issue by pww1971** [andrewssobral/bgslibrary#224]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pww1971** [comment]
The Bgslibrary library is for videos. Do you know how to target images? I would like to provide only one or two images and obtain the background. Is that okay

**Comment by andrewssobral** [comment]
Hello @pww1971 sorry for my late reply, you can find an exemple here:
https://github.com/andrewssobral/bgslibrary/blob/master/examples/Demo2.cpp
But unfortunately you need 2 images at least. The bgs methods provided in the library does not work with a single image. For this case you need a image segmentation method.
Hope this helps you,
Best,
Andrews
