### ISSUE TITLE
could you provide the Help documentation?

### ISSUE THREAD

**Issue by joefung** [andrewssobral/bgslibrary#25]
I try to compile with vs2012 but without success.it has been a lot of errors.I had modified the code but still a lot of errors .I did not find the help documentation on the website and I do not know how to be able to successfully apply it,.would you be able to offer the  user help documentation ? THX

**Comment by andrewssobral** [comment]
Hi @joefung there is a template project for both [VS2010](https://github.com/andrewssobral/bgslibrary/tree/master/vs2010) and [VS2013](https://github.com/andrewssobral/bgslibrary/tree/master/vs2013), I think you can built for VS2012 with a minor adjustments. An easy way is to open the *bgslibrary.vcxproj* file and make the following procedure:
* replace all occurrences of "C:\OpenCV2.4.10" with the correct path of your installed OpenCV;
* and, replace all occurrences of "vc10" (for VS2010) or "vc12" (for VS2013) with your Visual Studio version, i.e., "vc11" for VS2012.

I hope this helps you.
