### ISSUE TITLE
could you offer  the lib file ?

### ISSUE THREAD

**Issue by joefung** [andrewssobral/bgslibrary#26]
could you offer  the lib file directly be called by the C++ project which can omit the step to compile it? Indeed tried many times also modified the part of the code but still a lot of errors which led to unsuccessfully compile

**Comment by andrewssobral** [comment]
Hi @joefung thank you for your suggestion. I will check if there is an easy way to do it and I will let you updated about this.

**Comment by andrewssobral** [comment]
For Linux users, after CMake procedure, a **libbgs.so** is generated and then copied to **/usr/local/lib/lib**. The include files of **package_bgs** is copied to **/usr/local/include/package_bgs**.
For Windows users, a lib file called **bgs.lib** is also generated.
To do this, please follow the instructions in the [README_CMAKE_USERS.txt](https://github.com/andrewssobral/bgslibrary/blob/master/README_CMAKE_USERS.txt) file.

**Comment by zhixuanli** [comment]
I'm working on Ubuntu14.04, Opencv 3.2.0.
After the instruction of 

I have encountered the same question of libbgs.so
As you said above, I have done these:
`sudo cp -r package_bgs/ /usr/local/include/
sudo cp libbgs.so /usr/local/lib
`

But the time I try to `python Demo.py 
`

The problem's still there:

> Traceback (most recent call last):
  File "Demo.py", line 3, in <module>
    import libbgs
ImportError: No module named libbgs

Can you give me any suggestion?
Very thank you!
