### ISSUE TITLE
getting error while compiling Demo.cpp

### ISSUE THREAD

**Issue by warahul** [andrewssobral/bgslibrary#28]
I am trying to compile Demo.cpp with this command: g++ -o test1 Demo.cpp $(pkg-config opencv --cflags --libs)
and it throws out the error: undefined reference to `FrameDifferenceBGS::FrameDifferenceBGS()'
Please help me!!

**Comment by andrewssobral** [comment]
Hi @warahul, please refer to the **[readme_linux_users.txt](https://github.com/andrewssobral/bgslibrary/blob/master/README_LINUX_USERS.txt)** file.
The **[CMakeLists.txt](https://github.com/andrewssobral/bgslibrary/blob/master/CMakeLists.txt)** file contains the procedure to compile the **[Demo.cpp](https://github.com/andrewssobral/bgslibrary/blob/master/Demo.cpp)** file.
You can refer also to the **[example_linux](https://github.com/andrewssobral/bgslibrary/tree/master/example_linux)** folder for an additional example.
Hope this help you
