### ISSUE TITLE
library suitable for image segmentation?

### ISSUE THREAD

**Issue by nyotis** [andrewssobral/bgslibrary#29]
First off, awesome work!
How easy do you think it 'd be to make the library running for images?

**Comment by andrewssobral** [comment]
Hi @nyotis,
There is a [Demo](https://github.com/andrewssobral/bgslibrary/blob/master/Demo2.cpp) code of running the bgslibrary with a sequence of images. You can use also the [MFC GUI](https://github.com/andrewssobral/bgslibrary/releases/download/v1.9.2_x86_mfc_gui/bgslibrary_x86_v1.9.2_with_mfc_gui_v1.4.2.7z) with images, you need to check the checkbox "The input is..." and specify the start index, and the stop index.
Hope this help you,
Best regards,
Andrews
