### ISSUE TITLE
Getting errors with throw.cpp using Pixel Based Adaptive Segmenter

### ISSUE THREAD

**Issue by reddelta** [andrewssobral/bgslibrary#31]
The pixel based adaptive segmenter in my program is running well once it is compiled. Once the video was loaded, it is starting to get errors with throw.cpp and the marker always pointing at (PULONG_PTR)&ThisException.params ); 

If I hide bgs->processing(img_input, img_mask); using // then the program will run but wont be able to 
![1](https://cloud.githubusercontent.com/assets/13343783/8690964/3c59245a-2aee-11e5-861a-306a91dc52a4.jpg)
see the results. Just the video will continue to play.

**Comment by andrewssobral** [comment]
Hi, the PBAS method was removed from bgslibrary a long time ago due to patent breaking (ViBE). You can try the PBAS implementation available at: https://sites.google.com/site/pbassegmenter/home
