### ISSUE TITLE
Null Pointer error when using webcam.

### ISSUE THREAD

**Issue by dedenker** [andrewssobral/bgslibrary#32]
Compiled successful on Ubuntu 14.04 with OpenCV 2.4.11 (32 bit)
The demo run_video.sh runs perfect (I did not try other pre-recorded video's)
But when I want to use the webcam input, cli = bgs -uc -ca=0
I get:
OpenCV Error: Null pointer (Invalid pointer to file storage) in cvWriteString, file /home/{username}/opencv-2.4.11/modules/core/src/persistence.cpp, line 2997
std::exception:/home/{username}/opencv-2.4.11/modules/core/src/persistence.cpp:2997: error: (-27) Invalid pointer to file storage in function cvWriteString

**Comment by Romukas** [comment]
You probably need to create empty folder named config in the directory you are running your application from.

**Comment by andrewssobral** [comment]
Hi @dedenker , @Romukas  is right, the bgslibrary need a config folder to store the configuration files.
