### ISSUE TITLE
Possible problem and fix for DPTexture

### ISSUE THREAD

**Issue by jesuslop** [andrewssobral/bgslibrary#33]
Can't presently issue a pull request, but I think that in the line:

https://github.com/andrewssobral/bgslibrary/blob/master/package_bgs/dp/TextureBGS.cpp#L142

the operator () is invoked with arguments (x, y) but in 

https://github.com/andrewssobral/bgslibrary/blob/master/package_bgs/dp/Image.h#L322

the operator () assumens (row, colum):

  // pixel-level access using image(row, col)
  inline unsigned char& operator()(const int r, const int c)

so the correct invocation should have been with (y, x), and in fact with the change fixes an invalid memory reference error.

**Comment by andrewssobral** [comment]
Hi @jesuslop, Yes, you are right, the correct invocation should be fgMask(y,x). Thank you very much for your remark, I fixed this issue.
