### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by funnylo** [andrewssobral/bgslibrary#34]
![untitled](https://cloud.githubusercontent.com/assets/16266106/11761439/0543078e-a0fe-11e5-8d96-19fa42a8f1a0.png)

Hi, can you tell me how to solve this problem??

**Comment by lingdd** [comment]
There are three main functions in demo.cpp, demo2.cpp and Main.cpp, You can comment the other file and make one main function run in one time.

**Comment by andrewssobral** [comment]
Thank you for your help @lingdd
