### ISSUE TITLE
Can't run demo on Linux

### ISSUE THREAD

**Issue by zshn25** [andrewssobral/bgslibrary#35]
I followed the steps from REAME_LINUX.txt for my Ubuntu 12.04 and the run_camera.sh was working. But the other two run_video and run_demo are not. I'm not getting any error. It just doesn't show anything.
```
./run_video.sh
```
![screenshot from 2015-12-21 15 04 31](https://cloud.githubusercontent.com/assets/5270999/11927662/2c5faf32-a7f4-11e5-931d-83e6c1c8b4fd.png)

It just shows the above output and nothing else.
```./run_demo.sh
```

![screenshot from 2015-12-21 15 07 13](https://cloud.githubusercontent.com/assets/5270999/11927709/8c6aaa08-a7f4-11e5-8324-f1f61d157a4a.png)

Same for run_demo.sh. I tried with other video data but it just doesn't show anything.

**Comment by zshn25** [comment]
Also, when I compile the cpp demos on Ubuntu, it throws this error
```
compiling Demo2.cpp
/tmp/ccgj6aeK.o: In function `main':
/home/zee/BackgroundOpenCv/Demo2.cpp:79: undefined reference to `FrameDifferenceBGS::FrameDifferenceBGS()'
collect2: error: ld returned 1 exit status
Output file => Demo2
```
![image](https://cloud.githubusercontent.com/assets/5270999/11928635/25042086-a7fb-11e5-83cc-75e3c3e8d679.png)

Please help!! Thanks.

**Comment by zengzhi2015** [comment]
Have you try to write your own image capturing sentences and incorporate the corresponding BSG class into your program. If this does not work, there may be some setting problems with the compiler or the environment.

发自我的 iPad

**Comment by zshn25** [comment]
No, but I tried all the given demos. Its showing same error with all of them. Can you tell me how to compile it? I used this line to compile
```
g++ -ggdb `pkg-config --cflags opencv` -o `basename Demo.cpp .cpp` Demo.cpp `pkg-config --libs opencv`
```

**Comment by datbkhn** [comment]
You should use cmake to generate makefile to compile demos, please refer bgslibrary/CMakeLists.txt to create your own CmakeLists.txt to compile Demo2.cpp.

**Comment by Romukas** [comment]
You get `undefined reference to FrameDifferenceBGS::FrameDifferenceBGS()` error because compiler doesn't know where to look for FrameDifferenceBGS object.
If you don't want to use makefiles just add corresponding cpp file to your compile command, i.e. 
g++ -ggdb \`pkg-config --cflags opencv\` -o \`basename Demo.cpp .cpp\` Demo.cpp package_bgs/FrameDifferenceBGS.cpp \`pkg-config --libs opencv\`

**Comment by zshn25** [comment]
Thanks a lot @Romukas, @datbkhn, @zengzhi2015. It worked with the above compilation command.
I'll didn't try using CmakeLists.txt but I'm pretty sure it'll work.
