### ISSUE TITLE
OpenCV Error: Null pointer (Invalid pointer to file storage) in cvWriteInt

### ISSUE THREAD

**Issue by lingdd** [andrewssobral/bgslibrary#36]
Hi, There are some errors when I run the vs2010 demo!
OpenCV Error: Null pointer (Invalid pointer to file storage) in cvWriteInt, file
 ..\..\..\..\opencv\modules\core\src\persistence.cpp, line 2964

**Comment by andrewssobral** [comment]
This error occurs when *config* folder does not exists. Thank you for reporting this issue.

**Comment by murari023** [comment]
Then how to solve this problem? In VS 2013 also i am facing the same issue. The solution is building but the setup is not running

**Comment by andrewssobral** [comment]
Hi @murari023 you need to create a **config** folder in your project path, bgslibrary use it to store the configuration files...

**Comment by Mikkke46** [comment]
Hello, i have the same problem. But the config exist folder.

**Comment by JLiss13** [comment]
I had a very similar issue (I had an existing config folder) and it was solved when I deleted the XML I saved my calibration output information to and re-ran the program.

**Comment by anibalanto** [comment]
Hello! Solve the problem create manually the folder config inside the folder build.
