### ISSUE TITLE
cannot convert from 'const char [1]' to 'char

### ISSUE THREAD

**Issue by tolgayilmaz86** [andrewssobral/bgslibrary#37]
"cannot convert from 'const char [1]' to 'char *'Conversion from string literal loses const qualifier" 
error at PerformanceUtils class ImageROC and PerformanceEvaluation functions while compiling with Qt Creator on windows 64 with opencv3. After commenting out these functions it compiles and works properly.

**Comment by andrewssobral** [comment]
Hi @tolgayilmaz86 thank you for reporting this issue, I will check this.
Do you have used the opencv3 branch of the bgslibrary?
Best regards,
Andrews

**Comment by tolgayilmaz86** [comment]
yes i am working with opencv3 as much as possible.

**Comment by andrewssobral** [comment]
Hi @tolgayilmaz86 please let me know if this error occur in the updated opencv3 branch.
I hope all goes well now.
