### ISSUE TITLE
Access Violation Reading

### ISSUE THREAD

**Issue by ibazkom** [andrewssobral/bgslibrary#38]
Been try to use this library, some of method worked, but others not. Basic method absolutely fine, i got no problem compile it and ran it. I got "access violation reading location" error when trying others package. Mostly the error comes in the function "operator" in RgbPixel Class. 
![bgs_error2](https://cloud.githubusercontent.com/assets/3023899/14057069/253a3040-f328-11e5-82f6-8a8b744092f0.png)
This happen in almost method dp package.
I'm following README_VISUAL_STUDIO_USERS.txt to generate visual studio project. Is it a bug or i'm doing something wrong?

Like in this picture below:
![bgs_error1](https://cloud.githubusercontent.com/assets/3023899/14043706/c1d6ad12-f2b9-11e5-92c0-0fc3f8047334.png)
i'm trying to use "DPWrenGABGS" method, and got that error.
Any help would be so much appreciated
Thanks

**Comment by ibazkom** [comment]
Well, this is error that i'm talking about
![bgs_error2](https://cloud.githubusercontent.com/assets/3023899/14056439/9d9f0088-f31e-11e5-9c4b-1f6f0ece48d1.png)

**Comment by andrewssobral** [comment]
Hi @ibazkom have you tried with [vs2010](https://github.com/andrewssobral/bgslibrary/tree/master/vs2010) or [vs2013](https://github.com/andrewssobral/bgslibrary/tree/master/vs2013) template project?

**Comment by andrewssobral** [comment]
You can also generate a template project for visual studio using CMake. To do this, you can follow the instructions in [README_CMAKE_USERS.tx](https://github.com/andrewssobral/bgslibrary/blob/master/README_CMAKE_USERS.txt) file.
