### ISSUE TITLE
NOT Compatible with OpenCV3+

### ISSUE THREAD

**Issue by jiapei100** [andrewssobral/bgslibrary#40]
At least, one issue can be found at  http://code.opencv.org/issues/2778

Cheers
Pei

**Comment by jiapei100** [comment]
https://github.com/andrewssobral/bgslibrary/tree/opencv3

**Comment by andrewssobral** [comment]
Hi @jiapei100 sorry for my delayed response, yes there is a bgslibrary branch for opencv3. Maybe I'll put the current master branch to a new branch called opencv2.4, and next I'll put the opencv3 branch in the master branch. Thank you
