### ISSUE TITLE
bgslibrary opencv3 NO rule to install...

### ISSUE THREAD

**Issue by jiapei100** [andrewssobral/bgslibrary#42]
Installing with make install...

========================= Installation results ===========================
make: *** No rule to make target 'install'.  Stop.

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

**Comment by andrewssobral** [comment]
Hi @jiapei100,
I updated the [CMakeLists.txt](https://github.com/andrewssobral/bgslibrary/blob/opencv3/CMakeLists.txt) file for the opencv3 branch.
After **./make install** you need to copy the **config** folder from bgslibrary repository to your working place.
