### ISSUE TITLE
MixtureOfGaussianV1BGS and MixtureOfGaussianV2BGS are they the same?

### ISSUE THREAD

**Issue by mariantonia** [andrewssobral/bgslibrary#43]
I looked up both files and I realize they are the same

"
mog(img_input, img_foreground, alpha);
  
  cv::Mat img_background;
  mog.getBackgroundImage(img_background);
"
Why is that?

**Comment by zengzhi2015** [comment]
Hi, it seems that they are not the same. Please look at the .h file. In the MOG1, there is a member cv::BackgroundSubtractorMOG mog; However, in the MOG, the member is cv::BackgroundSubtractorMOG2 mog. I think these two classes are different.
Hope this explanation helps.
