### ISSUE TITLE
What is the official branch for OpenCV3.1.0?

### ISSUE THREAD

**Issue by gustavovelascoh** [andrewssobral/bgslibrary#45]
Hi, I've found that there are two branches regarding OpenCV 3, **opencv3** and **opencv3.x**. What will be official for supporting OpenCV 3.1+? Or Is there any reason for preserve both?

**Comment by andrewssobral** [comment]
Hi @gustavovelascoh the official branch for OpenCV 3.1+ is [opencv3](https://github.com/andrewssobral/bgslibrary/tree/opencv3). I disabled the opencv3.x branch.
