### ISSUE TITLE
cmake on linux shows OpenCV version is not compatible: 3.1.0

### ISSUE THREAD

**Issue by muglikar** [andrewssobral/bgslibrary#46]
cmake on linux shows OpenCV version is not compatible: 3.1.0

CMake Error at CMakeLists.txt:28 (message):
  OpenCV version is not compatible: 3.1.0

**Comment by muglikar** [comment]
Commenting the lines related to OpenCV version not compatible in CMakeLists.txt gives this error:

#if(${OpenCV_VERSION} VERSION_EQUAL 3 OR ${OpenCV_VERSION} VERSION_GREATER 3)
#  message (FATAL_ERROR "OpenCV version is not compatible: ${OpenCV_VERSION}")
#endif()

New Error Now after using 'make':

[  1%] Building CXX object CMakeFiles/bgs.dir/FrameProcessor.cpp.o
In file included from /home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/FrameProcessor.h:29:0,
                 from /home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/FrameProcessor.cpp:17:
/home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/package_bgs/MixtureOfGaussianV1BGS.h:30:7: error: ‘BackgroundSubtractorMOG’ in namespace ‘cv’ does not name a type
   cv::BackgroundSubtractorMOG mog;
       ^
In file included from /home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/FrameProcessor.h:30:0,
                 from /home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/FrameProcessor.cpp:17:
/home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/package_bgs/MixtureOfGaussianV2BGS.h:30:32: error: cannot declare field ‘MixtureOfGaussianV2BGS::mog’ to be of abstract type ‘cv::BackgroundSubtractorMOG2’
   cv::BackgroundSubtractorMOG2 mog;
                                ^
In file included from /usr/local/include/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv2/opencv.hpp:49,
                 from /home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/IFrameProcessor.h:19,
                 from /home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/FrameProcessor.h:20,
                 from /home/anand/Documents/opencv/ext_projects/vehicleVolume/bgslibrary/FrameProcessor.cpp:17:
/usr/local/include/opencv2/video/background_segm.hpp:90:20: note:   because the following virtual functions are pure within ‘cv::BackgroundSubtractorMOG2’:
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^
/usr/local/include/opencv2/video/background_segm.hpp:72:26: note: 	virtual void cv::BackgroundSubtractor::apply(cv::InputArray, cv::OutputArray, double)
     CV_WRAP virtual void apply(InputArray image, OutputArray fgmask, double learningRate=-1) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:81:26: note: 	virtual void cv::BackgroundSubtractor::getBackgroundImage(cv::OutputArray) const
     CV_WRAP virtual void getBackgroundImage(OutputArray backgroundImage) const = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:95:25: note: 	virtual int cv::BackgroundSubtractorMOG2::getHistory() const
     CV_WRAP virtual int getHistory() const = 0;
                         ^
/usr/local/include/opencv2/video/background_segm.hpp:98:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setHistory(int)
     CV_WRAP virtual void setHistory(int history) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:102:25: note: 	virtual int cv::BackgroundSubtractorMOG2::getNMixtures() const
     CV_WRAP virtual int getNMixtures() const = 0;
                         ^
/usr/local/include/opencv2/video/background_segm.hpp:107:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setNMixtures(int)
     CV_WRAP virtual void setNMixtures(int nmixtures) = 0;//needs reinitialization!
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:115:28: note: 	virtual double cv::BackgroundSubtractorMOG2::getBackgroundRatio() const
     CV_WRAP virtual double getBackgroundRatio() const = 0;
                            ^
/usr/local/include/opencv2/video/background_segm.hpp:118:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setBackgroundRatio(double)
     CV_WRAP virtual void setBackgroundRatio(double ratio) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:125:28: note: 	virtual double cv::BackgroundSubtractorMOG2::getVarThreshold() const
     CV_WRAP virtual double getVarThreshold() const = 0;
                            ^
/usr/local/include/opencv2/video/background_segm.hpp:128:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setVarThreshold(double)
     CV_WRAP virtual void setVarThreshold(double varThreshold) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:138:28: note: 	virtual double cv::BackgroundSubtractorMOG2::getVarThresholdGen() const
     CV_WRAP virtual double getVarThresholdGen() const = 0;
                            ^
/usr/local/include/opencv2/video/background_segm.hpp:141:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setVarThresholdGen(double)
     CV_WRAP virtual void setVarThresholdGen(double varThresholdGen) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:145:28: note: 	virtual double cv::BackgroundSubtractorMOG2::getVarInit() const
     CV_WRAP virtual double getVarInit() const = 0;
                            ^
/usr/local/include/opencv2/video/background_segm.hpp:148:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setVarInit(double)
     CV_WRAP virtual void setVarInit(double varInit) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:150:28: note: 	virtual double cv::BackgroundSubtractorMOG2::getVarMin() const
     CV_WRAP virtual double getVarMin() const = 0;
                            ^
/usr/local/include/opencv2/video/background_segm.hpp:151:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setVarMin(double)
     CV_WRAP virtual void setVarMin(double varMin) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:153:28: note: 	virtual double cv::BackgroundSubtractorMOG2::getVarMax() const
     CV_WRAP virtual double getVarMax() const = 0;
                            ^
/usr/local/include/opencv2/video/background_segm.hpp:154:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setVarMax(double)
     CV_WRAP virtual void setVarMax(double varMax) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:162:28: note: 	virtual double cv::BackgroundSubtractorMOG2::getComplexityReductionThreshold() const
     CV_WRAP virtual double getComplexityReductionThreshold() const = 0;
                            ^
/usr/local/include/opencv2/video/background_segm.hpp:165:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setComplexityReductionThreshold(double)
     CV_WRAP virtual void setComplexityReductionThreshold(double ct) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:172:26: note: 	virtual bool cv::BackgroundSubtractorMOG2::getDetectShadows() const
     CV_WRAP virtual bool getDetectShadows() const = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:175:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setDetectShadows(bool)
     CV_WRAP virtual void setDetectShadows(bool detectShadows) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:182:25: note: 	virtual int cv::BackgroundSubtractorMOG2::getShadowValue() const
     CV_WRAP virtual int getShadowValue() const = 0;
                         ^
/usr/local/include/opencv2/video/background_segm.hpp:185:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setShadowValue(int)
     CV_WRAP virtual void setShadowValue(int value) = 0;
                          ^
/usr/local/include/opencv2/video/background_segm.hpp:194:28: note: 	virtual double cv::BackgroundSubtractorMOG2::getShadowThreshold() const
     CV_WRAP virtual double getShadowThreshold() const = 0;
                            ^
/usr/local/include/opencv2/video/background_segm.hpp:197:26: note: 	virtual void cv::BackgroundSubtractorMOG2::setShadowThreshold(double)
     CV_WRAP virtual void setShadowThreshold(double threshold) = 0;
                          ^
CMakeFiles/bgs.dir/build.make:54: recipe for target 'CMakeFiles/bgs.dir/FrameProcessor.cpp.o' failed
make[2]: *** [CMakeFiles/bgs.dir/FrameProcessor.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/bgs.dir/all' failed
make[1]: *** [CMakeFiles/bgs.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by andrewssobral** [comment]
Hi @muglikar please see this issue https://github.com/andrewssobral/bgslibrary/issues/44
