### ISSUE TITLE
error: expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by jiapei100** [andrewssobral/bgslibrary#49]
Hi, Andrew:

I upgraded from Ubuntu 14.04 to 16.04, with GCC 5.4.0 + OpenCV 3.1.0, I failed to build the bgslibrary, with the following error messages:

> .../package_bgs/dp/Bgs.h:40: error: expected unqualified-id before numeric constant     static const int BACKGROUND = 0; 
> .../package_bgs/dp/Bgs.h:41: error: expected unqualified-id before numeric constant
>     static const int FOREGROUND = 255;

it looks like this file **dp/Bgs.h**, the following 2 lines 

```
static const int BACKGROUND = 0;
static const int FOREGROUND = 255;
```

is buggy, which seems to be weird to me....

Any suggestions?

Cheers
Pei

**Comment by andrewssobral** [comment]
Hi @jiapei100 sorry for my late response and thank you for the information.
I have built the bgslibrary (opencv3 branch) on Ubuntu 16:04 without errors, you can check in my latest docker image available at https://hub.docker.com/r/andrewssobral/bgslibrary_opencv3/
this docker image contains:
Ubuntu 16.04 + GCC 5.4.0 + VNC + OpenCV 3.1.0 (+ contrib) + Python 2.7 + BGSLibrary

**Comment by andrewssobral** [comment]
Thank you also for the pull request:
https://github.com/andrewssobral/bgslibrary/pull/50
however, you will need to send it to the opencv3 branch instead of the master branch
