### ISSUE TITLE
Library files installed all directly under /usr/local/include/package_bgs/

### ISSUE THREAD

**Issue by dmelo** [andrewssobral/bgslibrary#53]
On the source code, the library files are placed inside sub directories, like `bgslibrary/package_bgs/[lb,ae,av,bl]``... After installing using the default parameters, all the library files get inside the same dir``/usr/local/include/package_bgs/``, which causes compilation error, because those files are still including other library files on the parent path:

```
LBAdaptiveSOM.h:#include "../IBGS.h"
LBFuzzyAdaptiveSOM.h:#include "../IBGS.h"
LBFuzzyGaussian.h:#include "../IBGS.h"
LBMixtureOfGaussians.h:#include "../IBGS.h"
LBSimpleGaussian.h:#include "../IBGS.h"
```

When I try to compile with these libraries I get the error:

```
/usr/local/include/package_bgs/LBAdaptiveSOM.h:25:21: fatal error: ../IBGS.h: No such file or directory
 #include "../IBGS.h"
                     ^
compilation terminated.
```

**Comment by andrewssobral** [comment]
Thank you @dmelo for reporting this issue, I will check it in the next few days.

**Comment by KrzysztofKryszczuk** [comment]
seems still not solved within the last "few = 2190" days

**Comment by andrewssobral** [comment]
Solved!

**Comment by andrewssobral** [comment]
For more info:
https://github.com/andrewssobral/bgslibrary-examples
