### ISSUE TITLE
Problem in Demo.cpp while building in VS 2013

### ISSUE THREAD

**Issue by murari023** [andrewssobral/bgslibrary#55]
I am trying to build the vs 2013 solution and while building the demo.cpp it is giving 2 errors  
1. error LNK1169: one or more multiply defined symbols found	C:\bgslibrary\RESULTS\bgslibrary.exe
2. error LNK2005: _main already defined in Demo.obj	C:\bgslibrary\vs2013\Main.obj

**Comment by andrewssobral** [comment]
Hi @murari023 thank you for reporting this issue...
Do you have created your own vs2013 project? or you have used the pre-created vs2013 project of the bgslibrary?
