### ISSUE TITLE
Missing Platform files for "BGSLibrary v2.0.0 with QT GUI"

### ISSUE THREAD

**Issue by aliufukyaman** [andrewssobral/bgslibrary#57]
Dear Sobral,

The application in "BGSLibrary v2.0.0 with QT GUI" does not work due to missing platform files for Windows, you may have point not to add it but it may be hard for someone to find the right version of the plugins (qwindows.dll ) for relevant Qt version, compiler type and architecture to make it work. Could you also provide the needed files with the package? (QTDir/../../plugins/platforms/qwindows.dll)

Thanks in advance.

**Comment by andrewssobral** [comment]
Thanks for reporting this issue @aliufukyaman , I am checking it and I will let you updated soon as possible.

**Comment by cartycrabber** [comment]
Is there any way to make it work for now?

**Comment by andrewssobral** [comment]
Hi @aliufukyaman and @cartycrabber , sorry for my late update.
Can you both check if copying and pasting the DLL file below in your working directory the QT GUI works fine?
```
https://sites.google.com/site/andrewssobral/qwindows.dll
```
Just to see if there is other missing DLL's in the package, so I can update **bgslibrary2_qtgui_opencv320_x64.zip** with all dependencies. Thanks in advance!

**Comment by aliufukyaman** [comment]
Hi Sobral,

Thanks for the fix. Yes it works, Of course it has to be in a folder named "platforms". 

Btw, The execution time in ms for per frame that exist at MFC version is so useful, to my opinion it would be great to be shown also on QT version.

Thanks for your interest.

**Comment by cartycrabber** [comment]
Placing that file in a folder named platforms in the main directory worked for me as well, thanks!

**Comment by andrewssobral** [comment]
Thanks @aliufukyaman and @cartycrabber , I am updating the **bgslibrary2_qtgui_opencv320_x64.zip** package. 
@aliufukyaman I will take your suggestion for the next update of the QT GUI. Thanks!

**Comment by mrgloom** [comment]
I'm using bgslibrary2_qtgui_opencv320_x64 and I get error:

> This application failed to start because it could not find or load the Qt platfo
>  rm plugin "windows"

**Comment by johnsietsma** [comment]
Just to confirm, as aliufukyaman suggested, I needed to create a "platforms" directory and move qwindows.dll into that folder to fix this error. So it seems there is still an issue with the QT zip.
