### ISSUE TITLE
It seems that bgslibrary doesn't have wrapper for the Java

### ISSUE THREAD

**Issue by Bahramudin** [andrewssobral/bgslibrary#58]
If there is no wrapper for the Java, then how can we use this in Java? Thanks!!

**Comment by andrewssobral** [comment]
Hi @Bahramudin , yes, the bgslibrary does not have java wrapper yet, just a java-based user interface, but I am working on this for the next major update.

**Comment by Bahramudin** [comment]
@andrewssobral That will be great, I am waiting for that. Hope to achieve in the soon next!!

**Comment by andrewssobral** [comment]
Hi @Bahramudin ,
I would like to inform you that the Java wrapper for the BGSLibrary 2 is out, please see:
https://github.com/andrewssobral/bgslibrary/wiki/Wrapper:-Java
Best

**Comment by Bahramudin** [comment]
@andrewssobral Thank You!!

**Comment by Bahramudin** [comment]
@andrewssobral  Could you please some more details about how to generate the wrapper for java in window step by step? I have tried a lot many times as you gave the docs before, but it was not  success, maybe there is something wrong. E.g: you said that _"Running CMAKE with Visual Studio 2015 and OpenCV 3.2.0 (x64)"_ CMAKE with Visual Studio? There is CMake GUI do you mean by that, or how to run it with Visual Studio, and also _Working directory: bgslibrary\wrapper_java_ there is 2 bgslibrary directory...

**Comment by Bahramudin** [comment]
@andrewssobral  Here I have some questions, I really did not understand your declaration about how to make Java wrapper. Can you please present better documentation about this? For example **what do you mean by:** _Running CMAKE with Visual Studio 2015 and OpenCV 3.2.0 (x64)_  **And also** where we can run the commands, I am a windows user.

**Comment by andrewssobral** [comment]
@Bahramudin , I make a tutorial video showing all steps for compiling the Java wrapper for Windows users.
All steps showed in the video are described here:
https://github.com/andrewssobral/bgslibrary/wiki/Wrapper:-Java
Please see the tutorial video here:
https://www.youtube.com/watch?v=yUTGxtzbn3A

**Comment by Bahramudin** [comment]
@andrewssobral I have tried your tutorial step by step, but at the end it was not success. It is the message of Visual Studio` ========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== ` And also this the message I got when do cmake `You have called ADD_LIBRARY for library libbgs without any source files. This typically indicates a problem with your CMakeLists.txt file`.

I am wonder why you don't do something like OpenCV, for example OpenCV has already done prebuild JAR file for Java, when you download and extract it, you will find a JAR file for Java, and very easily can use in you project, without any extra work, but if you want to include opencv_contrib, then you can do it with cmake and Visual Studio. Now if you can do the same like OpenCV, it will great for every one, because everyone don't want to install Visual Studio, it needs large space, any not good to do like this. It is good to create a JAR file for Java and put it for download, it can be very nice. Good Luck!!

**Comment by andrewssobral** [comment]
Hi @Bahramudin, this has already been done, please see "Download binaries" from:
https://github.com/andrewssobral/bgslibrary/wiki/Wrapper:-Java

Please, can you copy&paste here the Visual Studio error?

**Comment by Bahramudin** [comment]
@andrewssobral If has already done, then how to use, which .dll file we need and how to load the libs, and where is the JAR file of your project to be included in our project. I think it is not good way to everyone build the libs by themselves, because VS2015 of installing cmake and other things is really not easy for everyone to do, and also take lot of space, really useless, it is better to you create a prebuild jar file and corresponding .dll file, just something like OpenCV did,
