### ISSUE TITLE
Java_Warper

### ISSUE THREAD

**Issue by mtastal** [andrewssobral/bgslibrary#59]
Hi Andrew
Thank you for your great effort. I need to know how can I integrate this library with a java code. I have a java code that was built for vehicle counting  based on the MOG2 algorithm of opencv3.2. I need to replace this algorithm with a better one, and I need to try between all of your library algorithm listed . In other word, Is it possible to call an algorithm from your library to be integrated in a java code?If so, could u plz clarify how  this can be done step by step?

thanks in advance

**Comment by andrewssobral** [comment]
Hi @mtastal ,
Yes, you can integrate the bgslibrary in your Java code. 
You can download the pre-built binaries or compile the Java wrapper from scratch, please see:
https://github.com/andrewssobral/bgslibrary/wiki/Wrapper:-Java
I make a tutorial video showing all steps for compiling the Java wrapper for Windows users.
Please see the tutorial video here:
https://www.youtube.com/watch?v=yUTGxtzbn3A
Hope this help you,
Best
