### ISSUE TITLE
How can I use bgslibrary to support my project using opencv3.0?

### ISSUE THREAD

**Issue by Drdestiny** [andrewssobral/bgslibrary#62]
Hi!
**I know that this library supports opencv2.x. But I don't understand how to support my project using opencv3.0.**
Thanks!

**Comment by andrewssobral** [comment]
Hi @Drdestiny the library is fully compatible with 2.x and 3.x
You can find some additional information about how to use it in your project here:
https://github.com/andrewssobral/bgslibrary/wiki/How-to-integrate-BGSLibrary-in-your-own-CPP-code
Hope this help you,
Best

**Comment by Drdestiny** [comment]
Thank you very much!
