### ISSUE TITLE
BGSLibrary v2.0.0 with QT GUI - qwindows.dll is placed in wrong directory

### ISSUE THREAD

**Issue by mchtech** [andrewssobral/bgslibrary#63]
bgslibrary2_qtgui_opencv320_x64.zip
qwindows.dll should be placed in "platforms" folder (**in production environment**), not the root directory. Otherwise, the program will output an error：

```
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".
```

In development environment, it works normally, while in production environment, it exits with the error.

**Comment by andrewssobral** [comment]
Hi @mchtech , 
I just updated the current release of bgslibrary2_console_opencv320_x64 fixing this issue.
Thanks
