### ISSUE TITLE
OpenCV error while calling the bgs function 

### ISSUE THREAD

**Issue by ARUNSOORAJPS** [andrewssobral/bgslibrary#70]
Hi.. I installed BGS Library in ubuntu with python wrappers and when I tried to run the demo.py or any other python program, I was not able to call any bgs function. I am getting OpenCV null pointer error. Attaching the error message here. 

>>>bgs = libbgs.FrameDifference()
FrameDifference()
OpenCV Error: Null pointer (Invalid pointer to file storage) in cvWriteInt, file /home/arun/opencv/modules/core/src/persistance.cpp , line 4583 
Traceback (most recent call last):
  File "<stdin>.". line 1, in <module>
Runtime Error : /home/arun /..... (-27) Invalid pointer to file storage in function cvWriteInt

**Comment by Romukas** [comment]
Hi, you're probably missing _config_ folder.

**Comment by AlvarHHM** [comment]
@Romukas Could you elaborate it?
Ive encountered the same error

**Comment by andrewssobral** [comment]
Hi @AlvarHHM , the bgslibrary need a config folder to store the configuration files. After compiling the python wrapper, before running Demo.py, you need to create a config folder in the working directory.

**Comment by luochenshuang** [comment]
Eureka! It's exactly solved my problem. A _config_ folder is required where the VC++ Project file locate.
