### ISSUE TITLE
Background Subtractor Error Opencv 2.4.9

### ISSUE THREAD

**Issue by fuxSocial** [andrewssobral/bgslibrary#75]
I'm working on OpenCV 2.4.9 32 bit and I am getting the following linking error:
[LinkingError.txt](https://github.com/andrewssobral/bgslibrary/files/1066312/LinkingError.txt)
Here is my code:

[MOG.txt](https://github.com/andrewssobral/bgslibrary/files/1066313/MOG.txt)
Somehow I got the linking error. Please help me

**Comment by andrewssobral** [comment]
Hi @fuxSocial ,
This is a linking error, you need to check if your compiler have found the opencv libraries.
Can you inform your OS, Compiler, IDE, ... ?

**Comment by fuxSocial** [comment]
Hi @andrewssobral ,
I already fix it. Thank you.

**Comment by andrewssobral** [comment]
Thank you @fuxSocial
