### ISSUE TITLE
any config parameters

### ISSUE THREAD

**Issue by ashish1405** [andrewssobral/bgslibrary#81]
Hello Andrew,

First of all very nice work done. One question is, are there any parameters to configure when using own/other video? Because when we use our sample video, the subtraction is done fine, but the green outline like in dataset/video.avi is not displayed. BTW our sample video is zoomed in, so the vehicles are displayed very big in frame.

**Comment by andrewssobral** [comment]
Hi @ashish1405 
In fact, the green outline in dataset/video.avi comes from original video (downloaded from Youtube), not from bgslibrary. If you are using QT or MFC GUI, the video frames are automatically resized for better viewer, but the saved foreground masks or background model uses the original video resolution. However, if you are using the Java GUI, there is a parameter to set the frame resolution (please see "**input_resize_percent**" from VideoCapture.xml file). 
Thanks!
