### ISSUE TITLE
VS issue with compiling wrapper for Python 3.6

### ISSUE THREAD

**Issue by mttucl** [andrewssobral/bgslibrary#82]
When I try to compile bgslibrary.sln with Visual Studio v14.0 I get 3 errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2562	'fs::python::py_init': 'void' function returning a value	libbgs	C:\bgslibrary\wrapper_python\np_opencv_converter.cpp	24	

Error	C2562	'init': 'void' function returning a value	libbgs	C:\bgslibrary\wrapper_python\utils\conversion.cpp	28	

Error	C2562	'NDArrayConverter::init': 'void' function returning a value	libbgs	C:\bgslibrary\wrapper_python\utils\conversion.cpp	209	

```

I had a problem with cmake finding Boost lib file, and fixed it in CMakeLists (line 85) by adding 3 to python
`	find_package(Boost REQUIRED COMPONENTS python3)`

I'm not sure if it should work with Python 3 (it worked in Linux?) but it is great work and hope you can extend it to win-py3.

My system
OS: Windows 10 Pro and 7 Pro
Visual Studio 2015 (v14.0)
Python 3.6.2
Opencv 3.3.0
Boost 1.64.0
cmake 3.9

**Comment by andrewssobral** [comment]
Hi @mttucl ,
I've not tried yet with python 3.6, I will check this.

**Comment by andrewssobral** [comment]
Hi @mttucl ,
I fixed this issue in my last commit. 
It works fine now for Linux and macOS Sierra on both Python versions 2.x and 3.x.
Some fixes were made in *conversion.cpp*, *conversion.h* and *np_opencv_converter.cpp* files. I think it should works now for Windows users. 
Thanks

**Comment by mttucl** [comment]
Hi Andrew,
Everything is working great now. I just had to rename `libboost_python3-vc140-mt-1_64.lib` to `libboost_python-vc140-mt-1_64.lib` and copy it to the build folder to fix VS LNK1104 error. 

Thank you for taking the time to fix this.

**Comment by andrewssobral** [comment]
Perfect! Thank you @mttucl for your feedback!
