### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by llandiit** [andrewssobral/bgslibrary#88]
Hi
we have downloaded latest bgslibrary from git, We have correctly installed OPENCV 3.3.0. We are using C++ 4.4.7 GNU on CentOS. We have run cmake and then after running make we get the following error:

from /usr/bgslibrary/package_bgs/CodeBook.cpp:17:
/usr/bgslibrary/package_bgs/IBGS.h:48: error: ISO C++ forbids initialization of member ‘firstTime’
/usr/bgslibrary/package_bgs/IBGS.h:48: error: making ‘firstTime’ static
/usr/bgslibrary/package_bgs/IBGS.h:48: error: ISO C++ forbids in-class initialization of non-const static member ‘firstTime’
/usr/bgslibrary/package_bgs/IBGS.h:49: error: ISO C++ forbids initialization of member ‘showOutput’
/usr/bgslibrary/package_bgs/IBGS.h:49: error: making ‘showOutput’ static
/usr/bgslibrary/package_bgs/IBGS.h:49: error: ISO C++ forbids in-class initialization of non-const static member ‘showOutput’
In file included from /usr/bgslibrary/package_bgs/CodeBook.cpp:17:
/usr/bgslibrary/package_bgs/CodeBook.h:43: error: ISO C++ forbids initialization of member ‘DEFAULT_ALPHA’
/usr/bgslibrary/package_bgs/CodeBook.h:43: error: making ‘DEFAULT_ALPHA’ static
/usr/bgslibrary/package_bgs/CodeBook.h:44: error: floating-point literal cannot appear in a constant-expression
/usr/bgslibrary/package_bgs/CodeBook.h:44: error: ISO C++ forbids initialization of member ‘DEFAULT_BETA’
/usr/bgslibrary/package_bgs/CodeBook.h:44: error: making ‘DEFAULT_BETA’ static
/usr/bgslibrary/package_bgs/CodeBook.h:44: warning: ISO C++ forbids initialization of member constant ‘DEFAULT_BETA’ of non-integral type ‘const float’
/usr/bgslibrary/package_bgs/CodeBook.h:45: error: ISO C++ forbids initialization of member ‘DEFAULT_LEARNFRAMES’
/usr/bgslibrary/package_bgs/CodeBook.h:45: error: making ‘DEFAULT_LEARNFRAMES’ static
/usr/bgslibrary/package_bgs/CodeBook.h:46: error: ISO C++ forbids initialization of member ‘t’
/usr/bgslibrary/package_bgs/CodeBook.h:46: error: making ‘t’ static
/usr/bgslibrary/package_bgs/CodeBook.h:46: error: ISO C++ forbids in-class initialization of non-const static member ‘t’
/usr/bgslibrary/package_bgs/CodeBook.h:47: error: ISO C++ forbids initialization of member ‘learningFrames’
/usr/bgslibrary/package_bgs/CodeBook.h:47: error: making ‘learningFrames’ static
/usr/bgslibrary/package_bgs/CodeBook.h:47: error: ISO C++ forbids in-class initialization of non-const static member ‘learningFrames’
/usr/bgslibrary/package_bgs/CodeBook.h:48: error: ISO C++ forbids initialization of member ‘alpha’
/usr/bgslibrary/package_bgs/CodeBook.h:48: error: making ‘alpha’ static
/usr/bgslibrary/package_bgs/CodeBook.h:48: error: ISO C++ forbids in-class initialization of non-const static member ‘alpha’
/usr/bgslibrary/package_bgs/CodeBook.h:49: error: ISO C++ forbids initialization of member ‘beta’
/usr/bgslibrary/package_bgs/CodeBook.h:49: error: making ‘beta’ static
/usr/bgslibrary/package_bgs/CodeBook.h:49: error: ISO C++ forbids in-class initialization of non-const static member ‘beta’
/usr/bgslibrary/package_bgs/CodeBook.cpp: In constructor ‘bgslibrary::algorithms::CodeBook::CodeBook()’:
/usr/bgslibrary/package_bgs/CodeBook.cpp:22: error: ‘int bgslibrary::algorithms::CodeBook::t’ is a static data member; it can only be initialized at its definition
/usr/bgslibrary/package_bgs/CodeBook.cpp:22: error: ‘int bgslibrary::algorithms::CodeBook::learningFrames’ is a static data member; it can only be initialized at its definition
/usr/bgslibrary/package_bgs/CodeBook.cpp:22: error: ‘int bgslibrary::algorithms::CodeBook::alpha’ is a static data member; it can only be initialized at its definition
/usr/bgslibrary/package_bgs/CodeBook.cpp:22: error: ‘float bgslibrary::algorithms::CodeBook::beta’ is a static data member; it can only be initialized at its definition
/usr/bgslibrary/package_bgs/CodeBook.cpp: In member function ‘void bgslibrary::algorithms::CodeBook::update_cb(const cv::Mat&)’:
/usr/bgslibrary/package_bgs/CodeBook.cpp:87: warning: comparison between signed and unsigned integer expressions
/usr/bgslibrary/package_bgs/CodeBook.cpp:105: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::min’
/usr/bgslibrary/package_bgs/CodeBook.cpp:105: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::max’
/usr/bgslibrary/package_bgs/CodeBook.cpp:105: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::f’
/usr/bgslibrary/package_bgs/CodeBook.cpp:105: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::l’
/usr/bgslibrary/package_bgs/CodeBook.cpp:105: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::first’
/usr/bgslibrary/package_bgs/CodeBook.cpp:105: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::last’
/usr/bgslibrary/package_bgs/CodeBook.cpp:105: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::isStale’
/usr/bgslibrary/package_bgs/CodeBook.cpp: In member function ‘void bgslibrary::algorithms::CodeBook::fg_cb(const cv::Mat&, cv::Mat&)’:
/usr/bgslibrary/package_bgs/CodeBook.cpp:137: warning: comparison between signed and unsigned integer expressions
/usr/bgslibrary/package_bgs/CodeBook.cpp:151: error: expected primary-expression before ‘[’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp:151: error: expected primary-expression before ‘]’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp:151: error: expected primary-expression before ‘&’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp:151: error: ‘c’ was not declared in this scope
/usr/bgslibrary/package_bgs/CodeBook.cpp:156: warning: comparison between signed and unsigned integer expressions
/usr/bgslibrary/package_bgs/CodeBook.cpp:173: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::min’
/usr/bgslibrary/package_bgs/CodeBook.cpp:173: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::max’
/usr/bgslibrary/package_bgs/CodeBook.cpp:173: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::f’
/usr/bgslibrary/package_bgs/CodeBook.cpp:173: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::l’
/usr/bgslibrary/package_bgs/CodeBook.cpp:173: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::first’
/usr/bgslibrary/package_bgs/CodeBook.cpp:173: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::last’
/usr/bgslibrary/package_bgs/CodeBook.cpp:173: warning: missing initializer for member ‘bgslibrary::algorithms::codeword::isStale’
/usr/bgslibrary/package_bgs/CodeBook.cpp:183: error: expected primary-expression before ‘[’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp:183: error: expected primary-expression before ‘]’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp:183: error: expected primary-expression before ‘&’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp:189: error: expected primary-expression before ‘[’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp:189: error: expected primary-expression before ‘]’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp:189: error: expected primary-expression before ‘&’ token
/usr/bgslibrary/package_bgs/CodeBook.cpp: In member function ‘virtual void bgslibrary::algorithms::CodeBook::saveConfig()’:
/usr/bgslibrary/package_bgs/CodeBook.cpp:196: error: ‘nullptr’ was not declared in this scope
/usr/bgslibrary/package_bgs/CodeBook.cpp: In member function ‘virtual void bgslibrary::algorithms::CodeBook::loadConfig()’:
/usr/bgslibrary/package_bgs/CodeBook.cpp:208: error: ‘nullptr’ was not declared in this scope
make[2]: *** [CMakeFiles/libbgs.dir/package_bgs/CodeBook.cpp.o] Error 1
make[1]: *** [CMakeFiles/libbgs.dir/all] Error 2
make: *** [all] Error 2

Can you please guide us to solve the problem?
Thanks

**Comment by andrewssobral** [comment]
Hi @llandiit , I am sorry for my late feedback.
I think there is something wrong while compiling the source code with C++11 support.
Maybe the following post could help you:
https://stackoverflow.com/questions/10033373/c-error-nullptr-was-not-declared-in-this-scope-in-eclipse-ide
