### ISSUE TITLE
OpenCv Error

### ISSUE THREAD

**Issue by dudenas** [andrewssobral/bgslibrary#90]
> OpenCV Error: Null pointer (Invalid pointer to file storage) in cvWriteReal, file /tmp/opencv-20170825-90583-1pdhamg/opencv-3.3.0/modules/core/src/persistence.cpp, line 4633
> libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20170825-90583-1pdhamg/opencv-3.3.0/modules/core/src/persistence.cpp:4633: error: (-27) Invalid pointer to file storage in function cvWriteReal

I read that i need to have a config file in the directory where I run the bgslibrary_gui, but it did not help.

**Comment by andrewssobral** [comment]
Hi @dudenas , I am sorry for my late response.
Yes, you should have a `config` folder in the same path where your `bgslibrary_gui` binary is located. Try to put your generated binary from `/bgslibrary/gui_qt/build/` to `/bgslibrary/`.
