### ISSUE TITLE
how processing just part of image(ROI) and change PAWCS learning BG rate?

### ISSUE THREAD

**Issue by ardashir66** [andrewssobral/bgslibrary#92]
hello,
thank you for your nice library in advance and i want ask you two question:

1- how processing just part of image(ROI) in bgs methods ? when i using ROI rectangle, error happen in   CV_Assert(oInitImg.isContinuous());

2- how change PAWCS learning BG rate? i want learning background in each 1 hour once. how i do that?

**Comment by andrewssobral** [comment]
Hi @ardashir66 , 
Thank you for your interest into the bgslibrary, and I am sorry for my delayed feedback to you.
Please, see the answers below:

> 1- how processing just part of image(ROI) in bgs methods ? when i using ROI rectangle, error happen in CV_Assert(oInitImg.isContinuous());

You could do this in several ways. If you are using the the standard bgslibrary binary generated into the `bgslibrary/build/` folder, you can define the ROI by changing the `bgslibrary/config/VideoCapture.xml` file. More specifically, the following parameters:
```
<use_roi>0</use_roi>
<roi_defined>0</roi_defined>
<roi_x0>0</roi_x0>
<roi_y0>0</roi_y0>
<roi_x1>0</roi_x1>
<roi_y1>0</roi_y1>
```
by setting `use_roi=1` and `roi_defined=1`, then defining `roi_x0`, `roi_y0`, `roi_x1`, and `roi_y1`.

> 2- how change PAWCS learning BG rate? i want learning background in each 1 hour once. how i do that?

PAWCS has a lot of parameters, only some of them are available in the config file of the algorithm. Maybe you will need to manually modify some of PAWCS internal parameters, please see:
https://github.com/andrewssobral/bgslibrary/blob/master/package_bgs/LBSP/BackgroundSubtractorPAWCS.cpp
such as:
```
...
// local define used to specify the default lword/gword update rate (16 = like vibe)
#define DEFAULT_RESAMPLING_RATE (16)
//! parameters used to scale dynamic learning rate adjustments  ('T(x)')
#define FEEDBACK_T_DECR  (0.2500f)
#define FEEDBACK_T_INCR  (0.5000f)
#define FEEDBACK_T_LOWER (1.0000f)
#define FEEDBACK_T_UPPER (256.00f)
...
```
You can try to send a message to Pierre-Luc St-Charles (https://github.com/plstcharles, author of the PAWCS algorithm) to ask him more about the algorithm parameters.
Best regards

**Comment by ardashir66** [comment]
thank you so much for your answer and take your time 
best regards
