### ISSUE TITLE
About Compiling BGSLibrary by Visual Studio Express 2015

### ISSUE THREAD

**Issue by xurong1981** [andrewssobral/bgslibrary#94]
I wonder whether it is possible to compile BGSLibrary by Visual Studio Express 2015 in Windows ?

**Comment by andrewssobral** [comment]
Hi @xurong1981 ,
Yes, you can find a tutorial here:
https://github.com/andrewssobral/bgslibrary/wiki/Compiling-BGSLibrary-with-OpenCV-3.x-and-Visual-Studio-2015-from-CMAKE
Hope this help you,
Best regards

**Comment by xurong1981** [comment]
Thank you. Let me make a try.
