### ISSUE TITLE
About The SigemaDeltaBGS have some question.Please!

### ISSUE THREAD

**Issue by LunaHisi** [andrewssobral/bgslibrary#95]
I run it success in the vs2013+opencv3.1,but the image mask just appear 1/3 of the complete image at the  initial frame. It's just like 2/3 of the complete had be abandoned at the initial frame.Maybe the SigemaDelatBGS class had miss  some important parameter.I ask for help!If you have meet the same problem,we can discuss together too.Thanks!

**Comment by andrewssobral** [comment]
Hi @LunaHisi , I am sorry for my delayed feedback.
Maybe this error is related because you are using grayscale images instead of color images. Can you confirm that? 
Best regards

**Comment by LunaHisi** [comment]
Thanks for you feedback.This error had been solved.Just as what you said.I changed the sigled channel image.Thank you for the amount。





At 2017-11-13 07:12:15, "Andrews Sobral" <notifications@github.com> wrote:


Hi @LunaHisi , I am sorry for my delayed feedback.
Maybe this error is related because you are using grayscale images instead of color images. Can you confirm that?
Best regards
