### ISSUE TITLE
confused error:Library not loaded

### ISSUE THREAD

**Issue by icebear-mint** [andrewssobral/bgslibrary#98]
finished download and cmake with python2 done,after make successfulliy I run the instruction python Demo.py
and then error occur:
StaceydeMacBook-Air:bgslibrary Stacey_W$ python Demo.py
Traceback (most recent call last):
  File "Demo.py", line 3, in <module>
    import libbgs
ImportError: dlopen(/usr/local/bgslibrary/build/libbgs.so, 2): Library not loaded: @rpath/libopencv_stitching.3.3.dylib
  Referenced from: /usr/local/bgslibrary/build/libbgs.so
  Reason: image not found

and I use otool to see the Library Dependencies,so why it can't load the library??
/usr/local/bgslibrary/build/libbgs.so:
	
![2017-12-25 14 27 05](https://user-images.githubusercontent.com/33170430/34334239-b8c95b34-e97f-11e7-9c90-84c1bdcd90f6.png)

**Comment by icebear-mint** [comment]
finally I found the mistakes about my opencv.
There some trouble in my opencv linking.

**Comment by icebear-mint** [comment]
Someone meet the same questions as me can try to reinstall your opencv, and it may help

**Comment by andrewssobral** [comment]
Hi @icebear-mint , I am sorry for my delayed feedback. I'd like to thank you for reporting this issue. This may help someone with the same issue. Best
