### ISSUE TITLE
gui_qt application cannot run

### ISSUE THREAD

**Issue by yellgreniff** [andrewssobral/bgslibrary#99]
For building qt from scratch, I used the wiki page. However, the first step was `Click on 'Qt 5.6 64-bit for Desktop (MSVC 2015)'`. I downloaded Qt but couldn't find the file in the first step. So then I downloaded Qt 5.6. Then I just continued onto step 2. When I launched cmake in step 4. There was an error saying Qt5Widgets package cannot be found. I solved it by setting Qt5Widget_DIR to the Qt5Widgets folder in Qt5.6. Then everything went well without an error. But when I ran bgslibrary_gui.exe, there was an error saying "The code execution cannot proceed because opencv-world340.dll was not found. Reinstalling the program may fix this problem" I tried rebuilding the solution and moving opencv-world340.dll to current directory and adding opencv to PATH. Then the program prompted `The application was unable to start correctly(0xc000007b). Click OK to close the application`. Can someone help me with this? I just want to use the gui to compare different bgs algorithms.

**Comment by andrewssobral** [comment]
Hi @yellgreniff !
Did you tried to run the `bgslibrary_gui.exe` in the root folder of the bgslibrary project (where the `config` folder exists)? Thanks

**Comment by yellgreniff** [comment]
Oh i found that the error was using 32 bit dll file on 64bit program. Also I thought i had to build it from scratch. Sorry about that.
